### ISSUE TITLE
Build error on Windows 10, libtorch 1.8.1 + cuda 11.1

### ISSUE THREAD

**Issue by JessubKim** [LaurentMazare/tch-rs#342]
Hi, I'm having issues building a project that references tch 0.4.0 crate.

The following is the build error:

> error: linking with `link.exe` failed: exit code: 1120
>   |
>   = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.0.rcgu.o" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.1.rcgu.o" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.2.rcgu.o" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.3.rcgu.o" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.4.rcgu.o" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.5.rcgu.o" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.6.rcgu.o" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.7.rcgu.o" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.testproj.2xybw6zx-cgu.8.rcgu.o" "/OUT:C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.exe" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\testproj.42mu6n3iz5bvs0bj.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\NprTool\\segmentation\\testproj\\target\\release\\deps" "/LIBPATH:C:\\NprTool\\segmentation\\dependencies\\libtorch-win-shared-with-deps-1.8.1+cu111\\lib" "/LIBPATH:C:\\NprTool\\segmentation\\dependencies\\libtorch-win-shared-with-deps-1.8.1+cu111\\lib" "/LIBPATH:C:\\NprTool\\segmentation\\testproj\\target\\release\\build\\torch-sys-967a628005003935\\out" "/LIBPATH:C:\\NprTool\\segmentation\\testproj\\target\\release\\build\\bzip2-sys-d02ed63a9304b1c6\\out\\lib" "/LIBPATH:C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "torch_cuda.lib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libtch-27ec525110a41892.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libndarray-879e6dfb4696d778.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libmatrixmultiply-3e3526b4fe0d403e.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libnum_complex-fc2810130099134a.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libnum_integer-e4ab8cf2a7c89369.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libnum_traits-c153447edb3db987.rlib" 
> "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\librawpointer-d2eda640dd24dab7.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\librand-a3eaf83d02734ef2.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\librand_chacha-b4cec86452222b55.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libppv_lite86-b6d61364b0288e28.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\librand_core-c4f7e4d35d5dcb09.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libgetrandom-1d8b96553fe63f88.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libhalf-c8535851149f9aea.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libtorch_sys-fb27198155dd7a3e.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libzip-dea04b6c53831d1c.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libtime-cd826b7a67621548.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libwinapi-e090f588aff0f4db.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libbzip2-3fda01da9b130f80.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libbzip2_sys-14a992251d289dbc.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libflate2-5bde4fa5b1495821.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libminiz_oxide-4e560b3b9bc84196.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libadler-22de63120e1649f3.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libbyteorder-f28da62f8893a7a6.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libcrc32fast-c81a37c96905ea0f.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libcfg_if-336a12bb8707ed0d.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\libthiserror-2c3dc3f82c68124e.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\liblibc-ce03296a09ada2f7.rlib" "C:\\NprTool\\segmentation\\testproj\\target\\release\\deps\\liblazy_static-3f55f2d8b5948953.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-e5130808ccb074ce.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-580326a9fdffe4b1.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-a76d77b5d9ed4759.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-d5a5b7aa7eeea0b8.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-4b74b4985b95e6c8.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-b2d5eb0d27518d1c.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-8a162ec37e71ea47.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-45fb7c94b612099e.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-3c0db88c6c3c2080.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-ae8fea3b9ef7193c.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-44bd5dbe4e29964c.rlib" "C:\\Users\\JClave\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-2e1363d96f00dd60.rlib" "advapi32.lib" "torch_cuda.lib" "torch_cuda_cu.lib" "torch_cuda_cpp.lib" "torch.lib" "torch_cpu.lib" "c10.lib" "advapi32.lib" "bcrypt.lib" "cfgmgr32.lib" "credui.lib" "crypt32.lib" "cryptnet.lib" "fwpuclnt.lib" "kernel32.lib" "ncrypt.lib" "ntdll.lib" "secur32.lib" "user32.lib" "ws2_32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
>   = note:    Creating library C:\NprTool\segmentation\testproj\target\release\deps\testproj.lib and object C:\NprTool\segmentation\testproj\target\release\deps\testproj.exp
>           libtorch_sys-fb27198155dd7a3e.rlib(dummy_cuda_dependency.o) : error LNK2019: unresolved external symbol "void * __cdecl at::cuda::getCurrentCUDABlasHandle(void)" (?getCurrentCUDABlasHandle@cuda@at@@YAPEAXXZ) referenced in function dummy_cuda_dependency
>           C:\NprTool\segmentation\testproj\target\release\deps\testproj.exe : fatal error LNK1120: 1 unresolved externals

The build for tch succeeded but the linking failed.
Was wondering if anyone has a clue on this.

**Comment by LaurentMazare** [comment]
I don't have a gpu enabled windows box at hand so this is a bit hard to diagnose. It's likely that we're missing the shared library defining this symbol in the link flags. You could try finding which library actually defines it and then add it to torch-sys [build.rs](https://github.com/LaurentMazare/tch-rs/blob/3bebf87c8eaa5627131d7be5441521f8c49043e7/torch-sys/build.rs#L223).

A typical one I would try adding is c10_cuda.lb which can be done by adding the following line:
```
    println!("cargo:rustc-link-lib=c10_cuda");
```

**Comment by codeandkey** [comment]
I'm running into the same issue as well.

Windows 10
libtorch 1.8.1-cu102
CUDA toolkit 10.2.89
tch-rs 0.4.0

**Comment by guillaume-be** [comment]
I am facing the same issue attempting to upgrade to `tch 0.4.0`. 

I did some troubleshooting and here are some preliminary findings:
- The issue seems unrelated to the CUDA version. `tch 0.3.1` builds fine with `libtorch 1.7.2` with `CUDA11.1`
- The split of libtorch into multiple libraries starting from `1.8.x` leads to error for both `CUDA10.2` and `CUDA11.1`. Specifically, the inclusion of a new "dummy dependency" does not seem to work properly during the linking phase:
```cpp
#include<stdio.h>
#include<stdint.h>
using namespace std;
extern "C" {
    void dummy_cuda_dependency();
}

namespace at {
    namespace cuda {
        // void *getCurrentCUDABlasHandle();
        int warp_size();
    }
}
char * magma_strerror(int err);
void dummy_cuda_dependency() {
    // at::cuda::getCurrentCUDABlasHandle();
    at::cuda::warp_size();
}
```
Commenting the above lines related to `getCurrentCUDABlasHandle` allows building (and running) the library. Unfortunately the GPU is then not properly recognized at runtime so this is obviously not a solution. Replacing `getCurrentCUDABlasHandle` with another CUDA-specific function (for example `at::cuda::is_available()` leads to the same issue)

I looked for this function in the libraries being linked, and `getCurrentCUDABlasHandle` is in `torch_cuda_cu.lib`. This file is available on my system and the flag `use_cuda_cu=true` in
```rust
if use_cuda_cu {
  println!("cargo:rustc-link-lib=torch_cuda_cu");
}
```
I would therefore expect this file to be linked properly. 

I also tried manually adding a linking with `c10_cuda.lib` via:
```rust
println!("cargo:rustc-link-lib=c10_cuda");
```
 and replacing the dummy dependency with :
```cpp
namespace at {
    namespace cuda {
        int warp_size();
    }
}

namespace c10 {
    namespace cuda {
        void *getDefaultCUDAStream();
    }
}

char * magma_strerror(int err);
void dummy_cuda_dependency() {
    c10::cuda::getDefaultCUDAStream();
    at::cuda::warp_size();
}
```
But this returns a similar linking error:
```
  = note:    Creating library E:\tch-rs\target\debug\examples\basics.lib and object E:\Coding\tch-rs\target\debug\examples\basics.exp
          libtorch_sys-8435f872fc11ecf5.rlib(dummy_cuda_dependency.o) : error LNK2019: unresolved external symbol "void * __cdecl c10::cuda::getDefaultCUDAStream(void)" (?getDefaultCUDAStream@cuda@c10@@YAPEAXXZ) referenced in function dummy_cuda_dependency
          E:\tch-rs\target\debug\examples\basics.exe : fatal error LNK1120: 1 unresolved externals
```
