### ISSUE TITLE
Unable to compile torch-sys

### ISSUE THREAD

**Issue by IanMichaelAsh** [LaurentMazare/tch-rs#671]
Hi (and apologies for the build query),

I'm trying to build on Ubuntu 22.04 running in Windows WSL.

The  LibTorch I'm using is the 2.0.0 Cxx11 ABI for CUDA 11.8 downloaded from the PyTorch website. 

When I run cargo build on tch-rs, I'm getting a lengthy set of compilation errors (list below w/ middle snipped for size).

What I've checked:
- NVidia CUDA is installed and running correctly
- A basis C++ application using LibTorch compiles and runs
- The LIBTORCH and LD_LIBRARY_PATH variables are set correctly and are appearing in the command lines below as I would expect (LibTorch root is `/opt/libtorch`)
- I've tried adding LIBTORCH_INCLUDE and LIBTORCH_LIB, but this makes no difference. 

Can anyone shed light on the cause of the errors below?

Ian


`error: failed to run custom build command for `torch-sys v0.10.3`

Caused by:
  process didn't exit successfully: `/home/ian/repos/bert/target/debug/build/torch-sys-167877ac05fe0450/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TORCH_CUDA_VERSION
  cargo:rerun-if-env-changed=LIBTORCH
  cargo:rustc-link-search=native=/opt/libtorch/lib
  cargo:rerun-if-env-changed=LIBTORCH_INCLUDE
  cargo:rerun-if-env-changed=LIBTORCH_LIB
  cargo:rerun-if-changed=libtch/torch_api.cpp
  cargo:rerun-if-changed=libtch/torch_api.h
  cargo:rerun-if-changed=libtch/torch_api_generated.cpp.h
  cargo:rerun-if-changed=libtch/torch_api_generated.h
  cargo:rerun-if-changed=libtch/stb_image_write.h
  cargo:rerun-if-changed=libtch/stb_image_resize.h
  cargo:rerun-if-changed=libtch/stb_image.h
  cargo:rerun-if-env-changed=LIBTORCH_CXX11_ABI
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "/opt/libtorch/include" "-I" "/opt/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/opt/libtorch/lib" "-std=c++14" "-D_GLIBCXX_USE_CXX11_ABI=1" "-o" "/home/ian/repos/bert/target/debug/build/torch-sys-48a4aa0b1c425270/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "/opt/libtorch/include" "-I" "/opt/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/opt/libtorch/lib" "-std=c++14" "-D_GLIBCXX_USE_CXX11_ABI=1" "-o" "/home/ian/repos/bert/target/debug/build/torch-sys-48a4aa0b1c425270/out/libtch/dummy_cuda_dependency.o" "-c" "libtch/dummy_cuda_dependency.cpp"
  exit status: 0
  cargo:warning=In file included from libtch/torch_api.cpp:13:
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__flash_scaled_dot_product_attention(at::Tensor**, tensor, tensor, tensor, tensor, tensor, int64_t, int64_t, double, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:1049:29: error: ‘_flash_scaled_dot_product_attention’ is not a member of ‘torch’
  cargo:warning= 1049 |     auto outputs__ = torch::_flash_scaled_dot_product_attention(*query, *key, *value, *cum_seq_q, *cum_seq_k, max_q, max_k, dropout_p, (bool)is_causal);
  cargo:warning=      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__lstm_mps_out(at::Tensor**, tensor, tensor, tensor, tensor, tensor, tensor, at::Tensor**, int, at::Tensor**, int, int, int64_t, double, int, int, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:1425:102: error: invalid initialization of reference of type ‘const at::Tensor&’ from expression of type ‘std::vector<at::Tensor>’
  cargo:warning= 1425 |     auto outputs__ = torch::_lstm_mps_out(*out0, *out1, *out2, *out3, *out4, *input, of_carray_tensor(hx_data, hx_len), of_carray_tensor(params_data, params_len), (bool)has_biases, num_layers, dropout, (bool)train, (bool)bidirectional, (bool)batch_first);
  cargo:warning=      |                                                                                      ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=In file included from /opt/libtorch/include/ATen/Functions.h:234,
  cargo:warning=                 from /opt/libtorch/include/ATen/ExpandUtils.h:4,
  cargo:warning=                 from /opt/libtorch/include/torch/csrc/autograd/input_metadata.h:3,
  cargo:warning=                 from /opt/libtorch/include/torch/csrc/autograd/function.h:7,
  cargo:warning=                 from /opt/libtorch/include/torch/csrc/autograd/engine.h:11,
  cargo:warning=                 from libtch/torch_api.cpp:1:
  cargo:warning=/opt/libtorch/include/ATen/ops/_lstm_mps.h:31:247: note: in passing argument 7 of ‘std::tuple<at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&> at::_lstm_mps_out(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, const at::Tensor&, at::TensorList, at::TensorList, bool, int64_t, double, bool, bool, bool)’
  cargo:warning=   31 | inline ::std::tuple<at::Tensor &,at::Tensor &,at::Tensor &,at::Tensor &,at::Tensor &,at::Tensor &> _lstm_mps_out(at::Tensor & out0, at::Tensor & out1, at::Tensor & out2, at::Tensor & out3, at::Tensor & out4, at::Tensor & out5, const at::Tensor & input, at::TensorList hx, at::TensorList params, bool has_biases, int64_t num_layers, double dropout, bool train, bool bidirectional, bool batch_first) {
  cargo:warning=      |                                                                                                                                                                                                                                    ~~~~~~~~~~~~~~~~~~~^~~~~
  cargo:warning=In file included from libtch/torch_api.cpp:13:
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__mps_max_pool2d(at::Tensor**, tensor, int64_t*, int, int64_t*, int, int64_t*, int, int64_t*, int, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:1599:29: error: ‘_mps_max_pool2d’ is not a member of ‘torch’
  cargo:warning= 1599 |     auto outputs__ = torch::_mps_max_pool2d(*self, torch::IntArrayRef(kernel_size_data, kernel_size_len), torch::IntArrayRef(stride_data, stride_len), torch::IntArrayRef(padding_data, padding_len), torch::IntArrayRef(dilation_data, dilation_len), (bool)ceil_mode);
  cargo:warning=      |                             ^~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__mps_max_pool2d_out(at::Tensor**, tensor, tensor, int64_t*, int, int64_t*, int, int64_t*, int, int64_t*, int, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:1606:29: error: ‘_mps_max_pool2d_out’ is not a member of ‘torch’
  cargo:warning= 1606 |     auto outputs__ = torch::_mps_max_pool2d_out(*out, *self, torch::IntArrayRef(kernel_size_data, kernel_size_len), torch::IntArrayRef(stride_data, stride_len), torch::IntArrayRef(padding_data, padding_len), torch::IntArrayRef(dilation_data, dilation_len), (bool)ceil_mode);
  cargo:warning=      |                             ^~~~~~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__scaled_dot_product_attention_math(at::Tensor**, tensor, tensor, tensor, tensor, double, int, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:1941:166: error: invalid initialization of reference of type ‘const c10::optional<at::Tensor>&’ from expression of type ‘bool’
  cargo:warning= 1941 |     auto outputs__ = torch::_scaled_dot_product_attention_math(*query, *key, *value, (attn_mask ? *attn_mask : torch::Tensor()), dropout_p, (bool)need_attn_weights, (bool)is_causal);
  cargo:warning=      |                                                                                                                                                                      ^~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=In file included from /opt/libtorch/include/ATen/Functions.h:289,
  cargo:warning=                 from /opt/libtorch/include/ATen/ExpandUtils.h:4,
  cargo:warning=                 from /opt/libtorch/include/torch/csrc/autograd/input_metadata.h:3,
  cargo:warning=                 from /opt/libtorch/include/torch/csrc/autograd/function.h:7,
  cargo:warning=                 from /opt/libtorch/include/torch/csrc/autograd/engine.h:11,
  cargo:warning=                 from libtch/torch_api.cpp:1:
  cargo:warning=/opt/libtorch/include/ATen/ops/_scaled_dot_product_attention_math.h:26:281: note: in passing argument 7 of ‘std::tuple<at::Tensor, at::Tensor> at::_scaled_dot_product_attention_math(const at::Tensor&, const at::Tensor&, const at::Tensor&, const c10::optional<at::Tensor>&, double, bool, const c10::optional<at::Tensor>&)’
  cargo:warning=   26 | inline ::std::tuple<at::Tensor,at::Tensor> _scaled_dot_product_attention_math(const at::Tensor & query, const at::Tensor & key, const at::Tensor & value, const c10::optional<at::Tensor> & attn_mask={}, double dropout_p=0.0, bool is_causal=false, const c10::optional<at::Tensor> & dropout_mask={}) {
  cargo:warning=      |                                                                                                                                                                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
  cargo:warning=In file included from libtch/torch_api.cpp:13:
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__sparse_mask_helper(at::Tensor**, tensor, tensor)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2225:29: error: ‘_sparse_mask_helper’ is not a member of ‘torch’
  cargo:warning= 2225 |     auto outputs__ = torch::_sparse_mask_helper(*t, *mask_indices);
  cargo:warning=      |                             ^~~~~~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__sparse_mask_helper_out(at::Tensor**, tensor, tensor, tensor)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2232:29: error: ‘_sparse_mask_helper_out’ is not a member of ‘torch’
  cargo:warning= 2232 |     auto outputs__ = torch::_sparse_mask_helper_out(*out, *t, *mask_indices);
  cargo:warning=      |                             ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__symeig_helper(at::Tensor**, tensor, int, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2400:29: error: ‘_symeig_helper’ is not a member of ‘torch’
  cargo:warning= 2400 |     auto outputs__ = torch::_symeig_helper(*self, (bool)eigenvectors, (bool)upper);
  cargo:warning=      |                             ^~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__symeig_helper_out(at::Tensor**, tensor, tensor, tensor, int, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2408:29: error: ‘_symeig_helper_out’ is not a member of ‘torch’
  cargo:warning= 2408 |     auto outputs__ = torch::_symeig_helper_out(*out0, *out1, *self, (bool)eigenvectors, (bool)upper);
  cargo:warning=      |                             ^~~~~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__torch_cuda_cu_linker_symbol_op(at::Tensor**, tensor)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2583:29: error: ‘_torch_cuda_cu_linker_symbol_op’ is not a member of ‘torch’
  cargo:warning= 2583 |     auto outputs__ = torch::_torch_cuda_cu_linker_symbol_op(*self);
  cargo:warning=      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__torch_cuda_cu_linker_symbol_op_out(at::Tensor**, tensor, tensor)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2590:29: error: ‘_torch_cuda_cu_linker_symbol_op_out’ is not a member of ‘torch’
  cargo:warning= 2590 |     auto outputs__ = torch::_torch_cuda_cu_linker_symbol_op_out(*out, *self);
  cargo:warning=      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__upsample_bicubic2d_aa_backward_vec(at::Tensor**, tensor, int64_t*, int, int64_t*, int, int, double*, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2766:103: error: could not convert ‘((output_size_data == 0) ? c10::optional<c10::ArrayRef<long int> >((c10::nullopt, const c10::nullopt_t())) : c10::optional<c10::ArrayRef<long int> >(c10::ArrayRef<long int>(((const long int*)output_size_data), ((size_t)output_size_len))))’ from ‘c10::optional<c10::ArrayRef<long int> >’ to ‘at::IntArrayRef’ {aka ‘c10::ArrayRef<long int>’}
  cargo:warning= 2766 |     auto outputs__ = torch::_upsample_bicubic2d_aa_backward(*grad_output, output_size_data == nullptr ? c10::nullopt : c10::optional<torch::IntArrayRef>(torch::IntArrayRef(output_size_data, output_size_len)), torch::IntArrayRef(input_size_data, input_size_len), (bool)align_corners, at::ArrayRef<double>(scale_factors_data, scale_factors_len));
  cargo:warning=      |                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                                                                                       |
  cargo:warning=      |                                                                                                       c10::optional<c10::ArrayRef<long int> >
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__upsample_bicubic2d_aa_backward_vec_out(at::Tensor**, tensor, tensor, int64_t*, int, int64_t*, int, int, double*, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2773:113: error: could not convert ‘((output_size_data == 0) ? c10::optional<c10::ArrayRef<long int> >((c10::nullopt, const c10::nullopt_t())) : c10::optional<c10::ArrayRef<long int> >(c10::ArrayRef<long int>(((const long int*)output_size_data), ((size_t)output_size_len))))’ from ‘c10::optional<c10::ArrayRef<long int> >’ to ‘at::IntArrayRef’ {aka ‘c10::ArrayRef<long int>’}
  cargo:warning= 2773 |     auto outputs__ = torch::_upsample_bicubic2d_aa_backward_out(*out, *grad_output, output_size_data == nullptr ? c10::nullopt : c10::optional<torch::IntArrayRef>(torch::IntArrayRef(output_size_data, output_size_len)), torch::IntArrayRef(input_size_data, input_size_len), (bool)align_corners, at::ArrayRef<double>(scale_factors_data, scale_factors_len));
  cargo:warning=      |                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                                                                                                 |
  cargo:warning=      |                                                                                                                 c10::optional<c10::ArrayRef<long int> >
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg__upsample_bicubic2d_aa_vec_out(at::Tensor**, tensor, tensor, int64_t*, int, int, double*, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:2794:98: error: could not convert ‘((output_size_data == 0) ? c10::optional<c10::ArrayRef<long int> >((c10::nullopt, const c10::nullopt_t())) : c10::optional<c10::ArrayRef<long int> >(c10::ArrayRef<long int>(((const long int*)output_size_data), ((size_t)output_size_len))))’ from ‘c10::optional<c10::ArrayRef<long int> >’ to ‘at::IntArrayRef’ {aka ‘c10::ArrayRef<long int>’}
  cargo:warning= 2794 |     auto outputs__ = torch::_upsample_bicubic2d_aa_out(*out, *input, output_size_data == nullptr ? c10::nullopt : c10::optional<torch::IntArrayRef>(torch::IntArrayRef(output_size_data, output_size_len)), (bool)align_corners, at::ArrayRef<double>(scale_factors_data, scale_factors_len));
  cargo:warning=      |                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

***** MIDDLE SNIPPED FOR SIZE - MANY PAGES OF SIMILAR ERRORS ****


int64_t*, int, int64_t*, int, int, double*, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:17876:101: error: could not convert ‘((output_size_data == 0) ? c10::optional<c10::ArrayRef<long int> >((c10::nullopt, const c10::nullopt_t())) : c10::optional<c10::ArrayRef<long int> >(c10::ArrayRef<long int>(((const long int*)output_size_data), ((size_t)output_size_len))))’ from ‘c10::optional<c10::ArrayRef<long int> >’ to ‘at::IntArrayRef’ {aka ‘c10::ArrayRef<long int>’}
  cargo:warning=17876 |     auto outputs__ = torch::upsample_trilinear3d_backward(*grad_output, output_size_data == nullptr ? c10::nullopt : c10::optional<torch::IntArrayRef>(torch::IntArrayRef(output_size_data, output_size_len)), torch::IntArrayRef(input_size_data, input_size_len), (bool)align_corners, at::ArrayRef<double>(scale_factors_data, scale_factors_len));
  cargo:warning=      |                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                                                                                     |
  cargo:warning=      |                                                                                                     c10::optional<c10::ArrayRef<long int> >
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_upsample_trilinear3d_backward_vec_out(at::Tensor**, tensor, tensor, int64_t*, int, int64_t*, int, int, double*, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:17883:111: error: could not convert ‘((output_size_data == 0) ? c10::optional<c10::ArrayRef<long int> >((c10::nullopt, const c10::nullopt_t())) : c10::optional<c10::ArrayRef<long int> >(c10::ArrayRef<long int>(((const long int*)output_size_data), ((size_t)output_size_len))))’ from ‘c10::optional<c10::ArrayRef<long int> >’ to ‘at::IntArrayRef’ {aka ‘c10::ArrayRef<long int>’}
  cargo:warning=17883 |     auto outputs__ = torch::upsample_trilinear3d_backward_out(*out, *grad_output, output_size_data == nullptr ? c10::nullopt : c10::optional<torch::IntArrayRef>(torch::IntArrayRef(output_size_data, output_size_len)), torch::IntArrayRef(input_size_data, input_size_len), (bool)align_corners, at::ArrayRef<double>(scale_factors_data, scale_factors_len));
  cargo:warning=      |                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                                                                                               |
  cargo:warning=      |                                                                                                               c10::optional<c10::ArrayRef<long int> >
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_upsample_trilinear3d_vec_out(at::Tensor**, tensor, tensor, int64_t*, int, int, double*, int)’:
  cargo:warning=libtch/torch_api_generated.cpp.h:17904:96: error: could not convert ‘((output_size_data == 0) ? c10::optional<c10::ArrayRef<long int> >((c10::nullopt, const c10::nullopt_t())) : c10::optional<c10::ArrayRef<long int> >(c10::ArrayRef<long int>(((const long int*)output_size_data), ((size_t)output_size_len))))’ from ‘c10::optional<c10::ArrayRef<long int> >’ to ‘at::IntArrayRef’ {aka ‘c10::ArrayRef<long int>’}
  cargo:warning=17904 |     auto outputs__ = torch::upsample_trilinear3d_out(*out, *input, output_size_data == nullptr ? c10::nullopt : c10::optional<torch::IntArrayRef>(torch::IntArrayRef(output_size_data, output_size_len)), (bool)align_corners, at::ArrayRef<double>(scale_factors_data, scale_factors_len));
  cargo:warning=      |                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                                                                                |
  cargo:warning=      |                                                                                                c10::optional<c10::ArrayRef<long int> >
  cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
  cargo:warning=   16 |     x \
  cargo:warning=      |     ^
  exit status: 1

  --- stderr


  error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "/opt/libtorch/include" "-I" "/opt/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/opt/libtorch/lib" "-std=c++14" "-D_GLIBCXX_USE_CXX11_ABI=1" "-o" "/home/ian/repos/bert/target/debug/build/torch-sys-48a4aa0b1c425270/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp" with args "c++" did not execute successfully (status code exit status: 1).`

**Comment by diptanu** [comment]
Hitting the same issue, it builds if I install a system-wide libtorch1.8 and libtorch-dev but when I run the binary it crashes saying undefined symbol.

**Comment by LaurentMazare** [comment]
> The LibTorch I'm using is the 2.0.0 Cxx11 ABI for CUDA 11.8 downloaded from the PyTorch website.
> ...  
> `error: failed to run custom build command for `torch-sys v0.10.3`

@IanMichaelAsh Not sure it's exactly the issue but it seems that you're building `tch 0.10.3` with `libtorch 2.0.0`. Each version of this crate works with a single version of libtorch and for `tch 0.10.3` you would want to use `libtorch 1.13.0` (see [here](https://crates.io/crates/tch/0.10.3)). If you want to use `libtorch 2.0.0` you should try with the `tch 0.11.x` versions.

**Comment by IanMichaelAsh** [comment]
@LaurentMazare Thanks for the helpful answer! Your root cause diagnosis was spot on.

There is a somewhat subtle issue at play here being caused by a non-obvious interplay with `rust-bert`:

My `cargo.toml` dependencies were set up as follows:
1. `tch = {version = "*"}`. (gah, the one time i'm not explicit on version!)
2. `rust-bert = {version = "0.20.0"}`. This is the latest published crate from rust-bert. 
 
Further, rust-bert was only bumped to LibTorch 2.0.0 in the last month, i.e. the crate is still compiling for LibTorch 1.13.0 whereas their HEAD is on 2.0.0. Both the crate docs and README on Github HEAD are correct in specifying dependencies of LibTorch v1.13.0, and 2.0.0 respectively .  

My mistake was the I read the GitHub install instructions and so configured LibTorch 2.0.0, but then ran my project against the published crate which still uses the earlier dependency. 

This mistake was compounded by not explicitly setting a version for tch-rs. This meant that tch-rs was able to silently downgrade its build to 1.13.0 to meet the dependency requirement being imposed by rust-bert.  

So, two alternate solutions that work:
- Use latest rust-bert from the repo using their unpublished `0.20.1-alpha `release, along with tch-rs and LibTorch on LibTorch 2.0.0; or
- Install LibTorch 1.13.0, build tch-rs for 1.13.0 bindings and depend on the published rust-bert crate.  

I can confirm the first option of building using `rust-bert 0.20.1-alpha` and a dependency chain build on LibTorch 2.0.0 works correctly. The second option obviously should as well as its all published crates, but I've not tested it myelf.

Ian

**Comment by diptanu** [comment]
Anyone hitting these issues - it's most likely a version mismatch of libtorch, tch and possibly rust_bart(if you are using it). Look at the version of the libtorch required by these libraries on the crates.io page and 1. pin the version of these crates 2. Download the specific version of libtorch.

For me these were - 
1. rust-bert = {version="0.20.0"}
2. tch = {version="0.10.3"}
3. libtorch - 1.13
