### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by yezuochang** [LaurentMazare/tch-rs#462]
libtorch was downloaded from https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.11.0%2Bcpu.zip

When compiling the package, the following errors and many other similar ones are reported.
```
  cargo:warning=libtch/torch_api_generated.cpp.h:8528:29: error: 'mkldnn_convolution_backward_weights' is not a member of 'torch'
```
```
cargo:warning=libtch/torch_api_generated.cpp.h:11222:111: error: too many arguments to function 'at::Tensor& at::softplus_backward_out(at::Tensor&, const at::Tensor&, const at::Tensor&, const c10::Scalar&, const c10::Scalar&)'
```

Cargo.toml
```
[package]
name = "sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15"
#tch="0.6.1"
tch = {git = "https://github.com/LaurentMazare/tch-rs"}
```

**Comment by LaurentMazare** [comment]
As mentioned in the readme, this crate is only compatible with pytorch 1.10.0. Support for the newly released 1.11.0 is ongoing and should be around in the next few days.

**Comment by LaurentMazare** [comment]
The latest version of this crate (0.7.0) should work with pytorch 1.11.0. Closing this issue for now, feel free to re-open if you still run into issues.
